import React from "react";
import SearchInput from "./SearchInput";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  SearchInput,
  "https://www.figma.com/design/SaJdIw4MWZrkKUeWAmrayD/FLUX-Components?node-id=1884-3264&m=dev",
  {
    props: {
      fieldLabel: figma.string("✏️  Field label"),
      instructions: figma.boolean("Has Instruction", {
        true: figma.string("✏️  Search tip text"),
        false: undefined,
      }),
      hasInstruction: figma.boolean("Has Instruction"),
    },
    example: (props) => (
      <SearchInput
        label={props.fieldLabel}
        hasInstructions={props.hasInstruction}
        instructions={props.instructions}
      />
    ),
  }
);
