import React from "react";
import SearchCard from "./SearchCard";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  SearchCard,
  "https://www.figma.com/design/iElKV1wMtj18K4Gc0dwzcY/Design-to-code-test-file?node-id=270-34853&m=dev",
  {
    props: {},
    example: () => <SearchCard />,
  }
);
